FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY main.py .

# Make sure the container has access to credentials
ENV GOOGLE_APPLICATION_CREDENTIALS=/secrets/credentials.json

# Create a directory for temporary files
RUN mkdir -p /tmp

# Set environment variable for the port
ENV PORT 8080

# Set the entrypoint command
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 main:app